#pragma once
#include "esp_system.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
esp_err_t esp_task_wdt_reset();
esp_err_t esp_task_wdt_add(TaskHandle_t);
esp_err_t esp_task_wdt_delete(TaskHandle_t);
esp_err_t esp_task_wdt_status(TaskHandle_t);
esp_err_t esp_task_wdt_deinit();
